### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by jprangenbergde**
Adds 8.1.0 as requirement for php

### CODE REVIEW

**Review by Ocramius — CHANGES_REQUESTED** [review]
Needs:

 * Updating `composer.lock`
 * Investigation of build failures

**Comment by Ocramius** [comment]
```
Error: Argument 1 of Laminas\ApiTools\OAuth2\Adapter\MongoAdapter::__construct expects Laminas\ApiTools\OAuth2\Adapter\MongoDB|array<string, int|string>, MongoDB provided (see https://psalm.dev/004)

```

This looks like an incorrect docblock on that constructor (missing import or missin leading  `\` in front of the type)

**Comment by Ocramius** [comment]
We probably need `laminas/coding-standard:~2.3.0` to get a successful PHP 8.1 installation.

**Comment by jprangenbergde** [comment]
> We probably need `laminas/coding-standard:~2.3.0` to get a successful PHP 8.1 installation.

Yes, and we need a PHP 8.1 compatible version of `laminas-api-tools/api-tools-oauth2`. But this package requires `laminas/laminas-test` which requires `laminas/laminas-console` which is readonly and not compatible to PHP 8.1.

**Comment by froschdesign** [comment]
@jprangenbergde 
> But this package requires `laminas/laminas-test` which requires `laminas/laminas-console`…

[Please check version 4.0.0 of laminas-test.](https://github.com/laminas/laminas-test/releases/tag/4.0.0)

**Comment by Ocramius** [comment]
Alternatively, we can configure CI to run 8.1 with `--ignore-platform-reqs` for now? 🤔

**Comment by jprangenbergde** [comment]
> Alternatively, we can configure CI to run 8.1 with `--ignore-platform-reqs` for now? 🤔

https://github.com/laminas-api-tools/api-tools-mvc-auth/pull/40/files#diff-3fb49ad00d3736f1ca8276f568f5d8bbe8c1604f6187ab5ecf921e1012f47c98

**Comment by Ocramius** [comment]
Awesome, so what is left is:
 * fixing that docblock
 * `vendor/bin/psalm --no-cache --update-baseline`
 * bumping `laminas/laminas-http` minimum version (or introducing a conflict with older versions)

Hopefully that will get us to green 😬

**Comment by Ocramius** [comment]
Ok, that last `composer.lock` update was too big (updated everything 😁)

I suggest re-doing the commit with just `composer update laminas/laminas-http`

**Comment by Ocramius** [comment]
Ok, looks like 7.3 cannot be supported together with 8.1 🤔

**Comment by Ocramius** [comment]
Ok, my suggestion to move this further/forward:

 * drop PHP 7.3 support (only 7.4 onwards)
 * bump `laminas/laminas-permissions-rbac` to its latest version

Not sure if further dependencies are problematic, but we'll have to see that as we move :-\ 

@samsonasik I could hold off a release until we also applied 7.4 type additions to this codebase, perhaps.

**Comment by Ocramius** [comment]
`laminas/laminas-permissions-rbac` needs upgrading here

**Comment by jprangenbergde** [comment]
> laminas/laminas-permissions-rbac

@Ocramius I have updated it. But we have a lot of other work to do. laminas-oauth2, laminas-api-problem…

**Comment by ghost** [comment]
What is the timeline for the task?

**Comment by Ocramius** [comment]
@FTI-Herbert you tell me: send a patch?

**Comment by ghost** [comment]
@Ocramius that's why we use a framework, so we don't have to do everything ourselves.

**Comment by jprangenbergde** [comment]
> @Ocramius that's why we use a framework, so we don't have to do everything ourselves.

WTF :-D You use a free framework, because you don't want to do everything by yourself? You know opensource?

**Comment by Ocramius** [comment]
@FTI-Herbert the framework is developed by the community: if you use the framework, you are part of the community :)

From your account activity, it doesn't seem that you are very familiar with how OSS works on github, but the general idea is "if you want to get something fixed, do it yourself, and everyone benefits from it".

That's why I suggested to step up and help :) 

All you see around here has been built that way for multiple decades now :muscle:

**Comment by ghost** [comment]
I do not quite understand why you call in the big guns.
I just asked one simple question after 3 month of inaction.
Even dependent on laminas we try to keep up with current php versions, which is by no means a trivial objective.

In your(the laminas contributer community) opinion questions allowed only for contributing "member of the community"? 
Well, in that case, we should also look at ways of making better use of our time and moving in a different direction in general.

Given this situation, i have to conclude unfortunately that, it is generally not worth the hassle to hold onto laminas.
Of course, be on one's high horse, that doesn't bother you.

**Pull request closed without merging**
